favicon: /favicon.ico


# Nav Menus
menu:
    Index: /
    Archives: /archives
    Tags: /tags
    Categories: /categories

# Nav Shortcut Icons
nav_icons:
    - ['/images/github.svg', 'https://github.com/narutohinata']
    - ['/images/rss.svg', '/atom.xml']

# Friend Links
friend_links:
    - ['narutohinata', 'This is a link', 'https://narutohinata.github.io/']

# About
about_info:
    name: "Chromer"
    avatar: "/images/avatar.png"

# Comment
# e.g disqus: seansun
disqus: narutohinata
duoshuo: 

# Analytics
google_analytics: Chromer
tencent_analytics: 
 
# Copyright Infomation
startyear: 2021
